export const FOCUSES: { key: number; name: string }[] = [
  { key: 1, name: "A trois mains" },
  { key: 2, name: "Absorbe l'énergie" },
  { key: 3, name: "Abuse de l'alchimie" },
  { key: 4, name: "Agit sans conséquence" },
  { key: 5, name: "Aime casser des choses" },
  { key: 6, name: "Ajuste le Léviathan" },
  { key: 7, name: "Apporte son soutien" },
  { key: 8, name: "Apporte son soutien" },
  { key: 9, name: "Apprend de l'adversité" },
  { key: 10, name: "Augmente la chair avec des greffes" },
  { key: 11, name: "Brandit un bouclier exotique" },
  { key: 12, name: "Brise les murs" },
  { key: 13, name: "Charge directement" },
  { key: 14, name: "Chasse" },
  { key: 15, name: "Chasse les Abhumains" },
  { key: 16, name: "Chasse les Mutants" },
  { key: 17, name: "Chevauche la foudre" },
  { key: 18, name: "Combat les automates" },
  { key: 19, name: "Commande les pouvoirs mentaux" },
  { key: 20, name: "Comprend les choses" },
  { key: 21, name: "Construit l'avenir" },
  { key: 22, name: "Contrôle la gravité" },
  { key: 23, name: "Contrôle les bêtes" },
  { key: 24, name: "Danse avec la matière noire" },
  { key: 25, name: "Descend de la noblesse" },
  { key: 26, name: "Devient énergie" },
  { key: 27, name: "Dirige" },
  { key: 28, name: "Dissimule la vérité" },
  { key: 29, name: "Défend la porte" },
  { key: 30, name: "Défend les faibles" },
  { key: 31, name: "Dévoue tout à la cause" },
  { key: 32, name: "Est tombé d'un autre monde" },
  { key: 33, name: "Existe partiellement en déphasage" },
  { key: 34, name: "Existe à deux endroits à la fois" },
  { key: 35, name: "Explore hier" },
  { key: 36, name: "Explore les eaux profondes" },
  { key: 37, name: "Explore les endroits sombres" },
  { key: 38, name: "Fabrique des illusions" },
  { key: 39, name: "Fabrique des objets uniques" },
  { key: 40, name: "Fait des merveilles" },
  { key: 41, name: "Fait des miracles" },
  { key: 42, name: "Fait des tours de force" },
  { key: 43, name: "Fait des tours de force" },
  { key: 44, name: "Fait quelque chose à partir de rien" },
  { key: 45, name: "Façonne le liquide" },
  { key: 46, name: "Focalise deux personnalités" },
  { key: 47, name: "Focalise l'esprit sur la matière" },
  { key: 48, name: "Forge un lien" },
  { key: 49, name: "Fréquente les morts" },
  { key: 50, name: "Fusionne l'esprit et la machine" },
  { key: 51, name: "Fusionne la chair et l'acier" },
  { key: 52, name: "Hurle à la lune" },
  { key: 53, name: "Joue des tours" },
  { key: 54, name: "Joue des tours" },
  { key: 55, name: "Manie deux armes à la fois" },
  { key: 56, name: "Manie le fouet" },
  { key: 57, name: "Manie le pouvoir avec précision" },
  { key: 58, name: "Manie les mots comme des armes" },
  { key: 59, name: "Manipule la force" },
  { key: 60, name: "Maîtrise la défense" },
  { key: 61, name: "Maîtrise les armes" },
  { key: 62, name: "Maîtrise les insectes" },
  { key: 63, name: "N'a pas besoin d'armes" },
  { key: 64, name: "Ne dit jamais la mort" },
  { key: 65, name: "Porte un carquois" },
  { key: 66, name: "Porte un halo de feu" },
  { key: 67, name: "Porte un manteau de glace" },
  { key: 68, name: "Possède un éclat de soleil" },
  { key: 69, name: "Possède un éclat du soleil" },
  { key: 70, name: "Rage" },
  { key: 71, name: "Rage" },
  { key: 72, name: "Rayonne de vitalité" },
  { key: 73, name: "Rayonne de vitalité" },
  { key: 74, name: "Regarde dans l'abîme" },
  { key: 75, name: "Rend la justice" },
  { key: 76, name: "Respire l'ombre" },
  { key: 77, name: "S'aventure dans la nuit" },
  { key: 78, name: "S'enfonce trop profondément" },
  { key: 79, name: "Se bat avec panache" },
  { key: 80, name: "Se bat avec une horde" },
  { key: 81, name: "Se bat salement" },
  { key: 82, name: "Se divertit" },
  { key: 83, name: "Se déplace comme un chat" },
  { key: 84, name: "Se refait une santé" },
  { key: 85, name: "Se refait. Ne dit jamais mourir" },
  { key: 86, name: "Se reforme complètement" },
  { key: 87, name: "Se trouve dans le cristal" },
  { key: 88, name: "Sentinelle de la communauté" },
  { key: 89, name: "Sépare l'esprit du corps" },
  { key: 90, name: "Tonnerre" },
  { key: 91, name: "Touche le ciel" },
  { key: 92, name: "Transmet la sagesse" },
  { key: 93, name: "Travaille dans les coulisses" },
  { key: 94, name: "Tue" },
  { key: 95, name: "Utilise le magnétisme" },
  { key: 96, name: "Vit dans la nature" },
  { key: 97, name: "Vit sur la route" },
  { key: 98, name: "Voit au-delà" },
  { key: 99, name: "Voyage dans le temps" },
  { key: 100, name: "affronte l'adversité" },
  { key: 101, name: "déchire les murs du monde" },
  { key: 102, name: "exploite le vide" },
  { key: 103, name: "lance avec une précision mortelle" },
  { key: 104, name: "parle aux machines" },
  { key: 105, name: "parle avec exaltation" },
  { key: 106, name: "parle avec une langue d'argent" },
  { key: 107, name: "parle à la datasphère" },
  { key: 108, name: "piège des proies mortelles" },
  { key: 109, name: "s'avance vers l'extérieur" },
  { key: 110, name: "se dresse comme un bastion" },
  { key: 111, name: "Siphonne le pouvoir" },
  { key: 112, name: "Émerge de l'obélisque" },
  { key: 113, name: "Évolue constamment" },
];

export const TYPES: { key: number; name: string }[] = [
  { key: 1, name: "Glaive" },
  { key: 2, name: "Nano" },
  { key: 3, name: "Jack" },
  { key: 4, name: "Arkus" },
  { key: 5, name: "Wright" },
  { key: 6, name: "Delve" },
];
